### ISSUE TITLE
How can I add custom content?

### ISSUE THREAD

**Issue by nickbe** [somewebmedia/hc-offcanvas-nav#30] opened 2020-03-11 15:00 UTC
How can I add custom content?
For example use the slide out for any other content without the menu? 

I've just replaced the old mobile menu with hc-offcanvas. However on the other page side we have a content sidebar which until now simply used the old off-canvas menu - but instead of the menu items, we simply displayed other contents.

**Comment by dominikkucharski** [comment] 2020-03-27 09:28
@nickbe did you found a solution?

**Comment by nickbe** [comment] 2020-03-27 10:03
Since it didn't seem to work out of the box and there's not documentation for this we dropped it. Regretably.

**Comment by dominikkucharski** [comment] 2020-03-27 10:41
@nickbe I think you can use any content, but it has to be wrapped in `<li>` tag. 

Example:
```
<nav id="mobile-nav">
<ul class="my-custom-class">
  <li>
    <div class="something">My custom content</div>
  </li>
</ul>
</nav>
```

As long as you will not use `<a>` tag in your custom content it will work great.

**Comment by nickbe** [comment] 2020-03-29 01:26
Yeah that's the probem. I need <a> tags - that's one issue and having to use it inside an <li> tag also gave us trouble. 

We've tried that out before, but I guess being able to use any content would be something that has to be implemented in the core routines first.

**Comment by somewebmedia** [comment] 2020-04-05 14:31
Duplicate of https://github.com/somewebmedia/hc-offcanvas-nav/issues/29
Please continue discussion there. Thanks.

**Closed by somewebmedia** 2020-04-05 14:31 UTC

**Comment by somewebmedia** [comment] 2020-04-05 18:50
@nickbe support for custom content has been added in the latest version.
